"""add payment_methods, update transactions for app payments

Revision ID: 815203f8f73a
Revises: 995d21ee762b
Create Date: 2026-07-08 15:38:19.587136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815203f8f73a'
down_revision: Union[str, Sequence[str], None] = '995d21ee762b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yookassa_payment_method_id', sa.String(), nullable=False),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('card_brand', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('bonus_used', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('paid_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('yookassa_payment_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_method_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('crestwave_sent', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('crestwave_event_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bonus_debited', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('transactions', 'program_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'payment_methods', ['payment_method_id'], ['id'])
    op.drop_column('transactions', 'serial')
    op.drop_column('transactions', 'payer_id')
    op.drop_column('transactions', 'payment_type')
    op.drop_column('transactions', 'amount')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.add_column('transactions', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('payment_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('payer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('serial', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'program_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'bonus_debited')
    op.drop_column('transactions', 'crestwave_event_id')
    op.drop_column('transactions', 'crestwave_sent')
    op.drop_column('transactions', 'payment_method_type')
    op.drop_column('transactions', 'yookassa_payment_id')
    op.drop_column('transactions', 'payment_method_id')
    op.drop_column('transactions', 'paid_amount')
    op.drop_column('transactions', 'bonus_used')
    op.drop_column('transactions', 'total_amount')
    op.drop_column('transactions', 'user_id')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
